version: "3.9"
services:
  users:
    image: ankit/auth_database:v1
    environment:
      POSTGRES_PASSWORD: dbpassword
    networks:
      internal:
        ipv4_address: 169.169.1.2
    ports:
     - 5432:5432
    volumes:
     - /pgdata:/pgdata
  
  executr:
   image: ankit/executr:v2
   command: "bash -c 'cd /root/executr && npm install && node .'"
   networks:
     internal:
       ipv4_address: 169.169.1.3
   ports:
      - 6970:6970
   volumes:
       - ~/projects/submittr/executr/:/root/executr/  

  authenticatr: 
   image: ankit/authenticatr:v2
   command: "bash -c 'cd /root/authenticatr && npm install && node .'"
   networks:
     internal:
       ipv4_address: 169.169.1.4
   ports:
     - 6969:6969
   volumes:
      - ~/projects/submittr/authenticatr/:/root/authenticatr/

  databasr:
   image: ankit/databasr:v2
   command: bash -c "su postgres -c 'pg_ctl -D /pgdata start' && cd /root/databasr && npm install && node ."
   networks:
      internal:
        ipv4_address: 169.169.1.5
   ports:
     - 6971:6971
   volumes:
     - ~/projects/submittr/databasr/:/root/databasr/
     - /databasrpg:/pgdata

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: 169.169.1.0/24
