version: "3.9"
services:
  users:
    image: ankit/auth_database:latest
    environment:
      POSTGRES_PASSWORD: dbpassword
    ports:
     - 5432:5432
    volumes:
     - /pgdata:/pgdata
  authenticatr: 
   image: ankit/authenticatr:test
   command: "bash -c 'cd /root/authenticatr && npm install && node .'"
   ports:
     - 6969:6969
   volumes:
      - .authenticatr/:/root/authenticatr
  executr:
   image: ankit/executr:test
   command: "bash -c 'cd /root/executr && npm install && node .'"
   ports:
      - 6970:6970
   volumes:
       - .executr/:/root/executr
  databasr:
   image: ankit/databasr:latest
   command: "bash -c 'apt update && apt install node && cd /root/databasr && npm install && node .'"
   ports:
     - 6971:6971
   volumes:
     - .databasr/:/root/databasr
     - /databasrpg:/pgdata  