version: 3

services:
    submittr:
    build: submittr
    ports:
      - "6972:6972"

  databasr: 
    build: databasr
    ports:
      - "6971:6971"
    env_file: 
      - databasr.env

  authenticatr: 
    build: authenticatr
    ports:
      - "6970:6970"
    env_file: 
      - authenticatr.env

  executr:
    build: executr/.
    ports:
      - "6969":"6969"

  

