version: "3.9"
services:
  users:
    image: user_data:v1
    build:
      context: ./user_data/    
    environment:
      POSTGRES_PASSWORD: dbpassword
    networks:
      internal:
        ipv4_address: 169.169.1.2
    ports:
     - 5432:5432
  
  executr:
   image: executr:v1
   build:
      context: ./executr/
   networks:
     internal:
       ipv4_address: 169.169.1.3
   ports:
      - 6970:6970
   volumes:
       - ./executr/:/root/executr/  

  authenticatr:
   image: authenticatr:v1
   build:
      context: ./authenticatr/
   networks:
     internal:
       ipv4_address: 169.169.1.4
   ports:
     - 6969:6969
   volumes:
      - ./authenticatr/:/root/authenticatr/

  databasr:
   image: databasr:v1
   build:
      context: ./databasr/
   networks:
      internal:
        ipv4_address: 169.169.1.5
   ports:
     - 6971:6971
   volumes:
     - ./databasr/:/root/databasr/

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: 169.169.1.0/24
