FROM postgres:latest
LABEL authon = "Ankit Das"
ENV POSTGRES_PASSWORD lolwa
ENV POSTGRES_DB user
COPY SQLscripts/ /docker-entrypoint-initdb.d/

RUN apt-get update
RUN apt-get upgrade
RUN apt-get install nodejs npm
RUN mkdir /databasr/
COPY package.json /databasr/package.json
RUN npm install /databasr/
COPY . /databasr
RUN node /databasr/api/